class TestEnv:
    ip = '123.4.5.6'
    user = 'robot'
    roles = ['admin', 'user']


AOP = {'amounts':'65', 'list' : ["Administrative","Admiralty-Plaintiff","All Other Professional Services Not Already Described","Anti-trust / Trade Regulation","Appellate","Arbitration / Mediation","Aviation","Banking / Financial Institutions Representation","Bankruptcy","BI/PI Defendant General Liability","BI/PI Defendant Medical Malpractice","BI/PI Defendant Other","BI/PI Defendant Products Liability","BI/PI Plaintiffs General Liability","BI/PI Plaintiffs Medical Malpractice","BI/PI Plaintiffs Other","BI/PI Plaintiffs Products Liability","Civil Rights / Discrimination","Collection / Repossession","Commercial Law","Communication / FCC","Construction / Building Contracts","Consumer Claims","Copyright / Trademark","Corp-General","Corporate Form","Criminal","Domestic Relations","Eminent Domain","Employee Benefits / ERISA","Entertainment / Sports","Environmental","Environmental Litigation","Foreign","Health Care","Immigration / Naturalization","Insurance Coverage","Investment Counseling / Money Management","Labor Law - Union","Labor Litigation - Defense","Labor Litigation - Management","Labor Litigation - Plaintiff","Litigation-General-Defense","Litigation-General-Plaintiff","Mergers & Acquisitions","Municipal / Government - Zoning","Municipal / Governmental - Other","Oil / Gas / Minerals","Patent","Probate / Wills / Estates","Public Utilities","Real Estate - Commercial","Real Estate - Escrow Agent","Real Estate - Residential","Real Estate - Syndication Development","Real Estate - Title Work","School Law","Securities / Bonds / Secured Transactions / Loans","Social Security Law","Taxation Corporate - Opinions","Taxation Corporation - Prep","Taxation-Individual","Water Rights Law","Workers Compensation - Defense","Workers Compensation - Plaintiff"]}    


ECC_EN = {'amountEndorsements':'342','list':["Commercial General Liability Coverage - Occurrence Form-Testing form",
"Commercial General Liability Coverage - Occurrence Form",
"Commercial General Liability - Claims Made",
"Amendment of Insurance Agreement - Known Injury or Damage",
"Exclusion - Violation of Statutes that Govern E-Mails, Fax, Phone Calls",
"Earlier Notice of Cancellation (60 days)",
"Coverage For Entities with Leased Workers",
"Electronic Data Liability Endorsement",
"Electronic Data Liability Endt - Loss of Elec Data Resulting Physical Injury",
"Primary and Noncontributory- Other Insurance Conditions", "Primary and Non-contributory- Other Insurance Conditions", "Additional Insured - Controlling Interest", "Additional Insured - Controlling Interest", "Additional Insured - Engineers Architects or Surveyors Endorsement", "Additional Insured - Engineers, Architects or Surveyors Endorsement", "Additional Insured - Owners, Lessees or Contractors Form A", "Additional Insured - Owners Lessees or Contractors Form A", "Additional Insured - Owners Lessees Form A", "Additional Insured - Owners Lessees Contractors", "Additional Insured - Owners Lessees or Contractors", "Blanket Additional Insured - Owners Lessees or Contractors", "Additional Insured - Owners Lessees or Contractors", "Blanket Additional Insured - Owners Lessees or Contractors", "Additional Insured - Owners Lessees Contractors", "Blanket Additional Insured - Owners Lessees Contractors", "Addt'l Insured - Owners Lessees or Contractors", "Additional Insured - Owners, Lessees, or Contractors- Scheduled Person or Or", "Additional Insured - Managers or Lessors of Premises", "Additional Insured-Manager of Lessors of Premises", "Additional Insured - Managers or Lessors of Premises", "Additional Insured- Manager of Lessors of Premises", "Blanket Addtl Insd State Political Subdivision", "Adtl Insd State Political Subdivisions", "Additional Insured-State or Governmental Agency or Subdivision", "Additional Insured - State or Political Subdivisions", "Additional Insured - State or Political Subdivision", "Additional Insured - State or Political Subdivision", "Blanket Additional Insured State Political Subdivision", "Additional Insured - Vendors", "Additional Insured - Vendors", "Additional Insured - Vendors", "Additional Insured - Mortgagee Assignee or Receiver", "Additional Insured - Mortgagee Assignee or Receiver", "Additional Insured - Mortgagee Assignee or Receiver", "Additional Insured - Oil or Gas Operations - Non-Operating Working Interests", "Additional Insured - Owners or Other Interests From Whom Land Leased", "Additional Insured - Owners or Other Interests From Whom Land Leased", "Additional Insured - Designated Person or Organization", "Addt'l Insd - Designated Person or Organization", "Additional Insured - Designated Person or Organization", "Additional Insured - Designated Person or Organization", "Additional Insured - Co-Owner of Premises", "Additional Insured - Co-Owner of Premises", "Additional Insured - Lessor of Leased Equipment", "Additional Insured - Lessor of Leased Equipment", "Additional Insured - Test Coverage", "Additional Insured - Lessor of Leased Equipment", "Additional Insured - Lessor of Leased Equipment", "Additional Insured - Grantor of Franchise", "Additional Insured - Grantor of Franchise", "Additional Insured - Oil or Gas Operations - Non-Operating Working Interests", "Addt'l Insd - Engineers Architects or Surveyors", "Additional Insured - Engineers Architects or Surveyors", "Additional Insured- Engineers Architects or Surveyors Not Engaged by Insured", "Additional Insured - Engineers Architects or Surveyors Not Engaged by Insured", "Addt't Insured - Automatic Status When Required in Construction", "Addt'l Insd - Construction Agreement", "Additional Insured - Owners Automatic Status", "Additional Insured - Owners, Lessees Or Contractors - Auto Status When Required", "Additional Insured - Lessor of Leased Equipment - Automatic Status", "Addt Insd - Lessor of Leased Equipment - Automatic Status", "Addtl Insd - Lessor of Leased Equipment", "Additional Insured - Lessor of Leased Equipment - Automatic Status When Required", "Additional Insured - Grantor of Licenses", "Additional Insured - Grantor of Licenses", "Addtl Insd Owners Lessees or Contractors Completed Operations", "Blanket Addtl Insd Owners Lessees or Contractors Completed Operations", "Additional Insured - Owners Lessees or Contractors - Completed Op's", "Blanket Additional Insured Owners Lessees or Contractors - Completed Operations", "Additional Insured - Owners Lessees - Completed Op's", "Blanket Addtl Insd-Owners Lessees or Contractors Completed Ops", "Additional Insured - Owners Lessees or Contractors Completed Operations", "Blanket Additional Insured - Owners, Lessees, or Contractors Completed Ops", "Additional Insured Owners Lessees Automatic Status Endorsement", "Blanket Additional Insured - Owners Lessees or Contractors", "Exclusion - Products or Completed Op's Hazards", "Exclusion - Access or Disclosure of Data", "Exclusion - Designated Products", "Exclusion - Coverage C - Medical Payments", "Exclusion - XCU", "Exclusion - XCU", "Exclusion - Fire Damage Legal Liability", "Exclusion - Fire Damage Legal Liability", "Employment Related Practices Exclusion", "Employment Related Practices Exclusion", "Total Pollution Exclusion", "Exclusion - Total Pollution", "Exclusion - Designated Op's (Wrap-up)", "Exclusion - Designated Operations (Wrap-up)", "Total Pollution Excl with a Hostile Fire Exception", "Inspection Appraisal and Survey Companies", "Inspection Appraisal and Survey Companies", "Exclusion - Testing or Consulting Errors & Omissions", "Exclusion - Testing or Consulting Errors & Omissions", "Exclusion - Construction Mgmt Erors & Omissions", "Exclusion - Construction Mgmt Erors & Omissions", "Exclusion - Engineers Architects or Surveyors", "Exclusion - Engineers, Architects or Surveyors", "Exclusion - Saline Substances Contamination", "Exclusion - Failure to Supply", "Exclusion - Failure to Supply", "Exclusion - Underground Resources and Equipment", "Exclusion - Underground Resources and Equipment", "Pesticide or Herbicide Applicators Coverage", "Pesticide or Herbicide Applicators Coverage", "Misdelivery of Liquid Products Coverage", "Limited Contractual Liability Coverage", "Exclusion - Contractors - Professional Liability", "Exclusion - Contractors - Professional Liability", "Snow Plow Operations Coverage Endorsement", "Waiver of Transfer of Right of Recovery Against Others to US", "Blanket Waiver of Transfer of Right of Recovery Against Others to US", "Waiver of Transfer of Right of Recovery Against Others to Us", "Blanket - Waiver of Transfer of Right of Recovery Against Others to Us", "Boats Endorsement", "Waiver of Governmental Immunity", "Contractual Liability - Railroads", "Amendment of Coverage Territory - Worldwide Coverage Endorsement", "Additional Scheduled Countries", "Additional Scheduled Countries", "Worldwide Coverage with Specified Exceptions", "Worldwide Coverage with Specified Exceptions", "Designated Construction Proj Gen Aggregate Limit", "Designated Construction Proj Gen Aggregate Limit", "Dedicated Aggregate - Per Project", "Designated Locations - General Aggregate", "Designated Locations - General Aggregate Limit", "Supplemental Extended Reporting Period", "Supplemental Extended Reporting Period", "Pollution Exclusion Amendment", "Pollution Exclusion Amendment", "Addtl Insd State or Political Subdivisions", "Additional Insured State or Political Subdivisions- OCP Policies", "PFAS Exclusion Endorsement", "Coverage for Injury to Co-Employees or Volunteer Workers", "Exclusion - Non Owned Watercraft", "Motor Vehicle Laws Endorsement", "Retroactive Dates for Scheduled Locations", "Professional Liability Form Claims Made", "Common Policy Conditions", "Nuclear Energy Liability Exclusion", "Extended Reporting Period Endorsement", "Specified Professional Services Endorsement.", "Claims Notice Document", "Service of Suit", "Service of Suit", "Minimum Earned Premium Endorsement", "Designated Professional Services Exclusion", "Compensation Collection Exclusion Endorsement", "Specific Joint Venture Participation Endorsement", "General Amendatory Endt", "Exclusion - Projects by a Related Person Firm or Organization", "Specified Project Exclusion Endorsement", "Specified Entity Exclusion", "Mold and Mildew Exclusion", "Amendment of Limits Endorsement Blanket", "Amendment of Limits Endorsement Project-Specific", "Dedicated Aggregate for a Designated Project", "Increased Limits Separate Retroactive Date", "Separate Limits Endorsement for Each Coverage Part", "Sub Contractor as Insured", "Reporting Period Endorsement", "Primary Insurance Endorsement - Designated Work or Projects", "Exclusion of Related Claims Endorsement", "Specific Circumstance Exclusion Endorsement", "Reimbursements Rebates and Allowable Costs Exclusion", "Mold Deductible Endorsement", "Automatic Waiver of Subrogation - also for E&O", "Knowledge of Occurrence", "Added Coverage Part - E&O", "Extended Policy Endorsement", "Extended Policy Endorsement", "Waiver of Subrogation - E&O", "Amendment of Policy Term Endorsement", "Material Change Endorsement", "Technology Based Services Coverage Endorsement", "LSRP Professional Liability Endorsement", "Professional Liability Claims Expense Limit", "Exclusion - Communicable Disease with Mold exception", "Common Policy Declarations Page", "Contractors Pollution Liability Form Occurrence", "Contractors Pollution Liability Form Claims Made", "Professional Liability Form Claims Made", "Common Policy Conditions", "Nuclear Energy Liability Exclusion", "Nuclear Energy Liability Test V", "Deductible Liability Insurance Endorsement", "Extended Reporting Period Endorsement", "Automatic Additional Insured Owners Lessees or Contractors", "Automatic Waiver of Subrogation", "Specified Professional Services Endorsement.", "Claims Notice Document", "Service of Suit", "Minimum Earned Premium Endorsement", "Extension of Coverage for Certain Occurrences - Nose for CGL", "Hired and Non-Owned Auto Liability $1M", "Hired and Non Owned Auto - 1mil/1mil limit", "Employers Liability (Stop Gap) 1/1 limit", "Gulf of Mexico Endorsement", "In REM Coverage Endorsement", "Non-Owned Watercraft Endorsement", "Products (Pollution) Liability Coverage Endorsement", "Employee Benefit Liability - 1mil/1mil limit", "New York Action Over Exclusion Endorsement", "Temporary Workers",
"Hired and Non-Owned Auto Liability Coverage - Specified Project Endorsement", "Amendment of Occurrence Definition", "Governmental Entity Endorsement", "Fellow Employee Amendment Endorsement", "Care Custody Control Amendment", "Bailees Coverage Form", "Injury to Temporary Volunteer or Casual Worker Exclusion", "Transportation of Cargo Pollution Endorsement", "Extension of Coverage for Certain Specified Claims (Nose for CPL)", "Contingent Transportation Pollution Liability Coverage", "Transportation at Jobsite Endorsement", "Additional Insured Endorsement - CPL", "Additional Insured Blanket - CPL", "Medical Monitoring Costs Endorsement", "Completed Operations Coverage Extension", "Schedule of Locations", "Schedule of Named Insureds", "Transportation Pollution Liability Endorsement", "Amendment of Cancellation Notice Endorsement uses endeavor to wording", "Exclusion of Services for a Related Person Firm or Organization", "Designated Premises Exclusion", "Specified Entity Exclusion", "Vacant Land/Rental Property Exclusion", "Pesticide/Herbicide/Sludge Applicator Endorsement", "30 Day NOC Endorsement - No Endeavor to wording", "Sample Coverage Pro", "Residential Operations Exclusion", "Water Intrusion Roofing Operations Exclusion", "Audit Endorsement", "Cancellation Endorsement", "Amendment of Named Insured Endr", "Amendment of Address Endorsement", "Amendment of Limits Endorsement Blanket", "Pyramiding of Limits Endorsement", "Low-Level Radioactive Waste Amendment amends exclusion to include low level", "Punitive or Exemplary Damages Amendment", "Designated Project Limitation Endorsement", "Designated Operations Exclusion.", "Primary and Non-Contributory Endorsement (project specific)", "Exclusion - Data Processing Equipment Data Media or Computer Programs", "Previously Reported Claims Endorsement", "Subsidence Exclusion", "Sample Disposal Liability Endorsement", "Designated Premises Pollution Endorsement", "Blanket Primary and Non-Contributory Endorsement", "Designated Operations Covered By A Consolidated Insurance Program", "Mold Sublimit Endorsement", "Broad Form Named Insured", "ECC Terrorism Cancellation Endorsement", "Paint Overspray Exclusion", "FLAT Cancellation Endorsement", "Reinstatement Endorsement", "Services or Gross Revenue Amendment", "Added Named Insured Endorsement", "Deleting Named Insured Endorsement", "Added Coverage Part - CGL", "Added Coverage Part - CPL", "Non-Owned Disposal Site Liability Endorsement", "Blanket Non-Owned Disposal Site Endorsement", "Designated Covered Operations", "Natural Resource Damage Endorsement", "Additional Insured Individual", "Waiver of Subrogation Individual", "Responsible Insured Definition Amendment Endorsement", "Additional Insured PNC and Notice of Cancellation Endorsement", "TRIA Reinstatement Endorsement", "Notification of Cancellation to Certificate Holders", "Mold Deductible Endorsement", "Virus or Bacteria Exclusion - CGL", "Virus or Bacteria Exclusion - CPL", "Virus or Bacteria Exclusion - PL", "Terrorism Coverage Added Endorsement", "Hired and Non-Owned Auto - 2M Limit", "Virginia Financial Resp Biosolids", "Material Change Endorsement - 60 Day", "Workers Compensation/Employers Liability Limitation Endorsement", "Waiver of Deductible Endorsement", "Cyber Liability Endorsement", "Governmental Immunity - Port Authority of NY & NJ", "Premium Audit Endorsement", "Communicable Disease Exclusion", "Excess Policy Form", "Excess Policy Declarations", "Excess Schedule of Forms & Endorsements", "Claims Notice Document", "Nuclear Energy Liability Exclusion", "Mold and Mildew Exclusion", "Employment Discrimination & Employment-Related Practices Exclusion", "Common Policy Conditions Endorsement", "Vehicle Exclusion - Excess Policy", "Additional Insureds - Owners Lessees or Contractors", "Automatic Additional Insured Owners Lessees or Contractors", "Waiver of Subrogation Endorsement", "Service of Suit", "Minimum Premium Endorsement", "New York Action Over Exclusion Endorsement", "Underlying Coverage Exclusion - Contractors Pollution Liability", "PFAS Exclusion Endorsement", "Underlying Coverage Exclusion - Professional Liability", "Schedule of Named Insureds", "General Amendatory Endorsement", "Amendment of Cancellation Notice Endorsement - Endeavor To", "Specified Entity Exclusion", "Excess 30 Day NOC Endorsement - No Endeavor To", "Excess Cancellation Endorsement", "Excess Amendment of Named Insured Endr", "Excess Amendment of Address", "Excess Amendment of Limit", "Insurers of the Underlying Insurance Amendment Endorsement", "Excess Terrorism Cancellation", "FLAT Cancellation Endorsement", "Reinstatement Endorsement", "Added Named Insured Endorsement", "Excess Extended Policy Endorsement", "Amendment of Policy Term Endorsement", "Additional Insured Individual", "Terrorism Reinstatement Endorsement", "Terrorism Coverage Added Endorsement", "Florida Terrorism Coverage Added Endorsement", "Signature Page", "Signature Page", "OFAC", "OFAC", "Trade or Economic Sanctions Endorsement", "Trade or Economic Sanctions Endorsement", "Spill Center Notice", "Virginia State Surplus Lines Notice"]}

ECC_VA = {
    'amountEndorsements': '25',
    'list': [
        "Common Policy Conditions",
        "Nuclear Energy Liability Exclusion",
        "Deductible Liability Insurance Endorsement",
        "Minimum Earned Premium Endorsement",
        "Automatic Additional Insured Owners Lessees or Contractors",
        "Automatic Waiver of Subrogation",
        "Transportation at Jobsite Endorsement",
        "Exclusion - Access or Disclosure of Data",
        "OFAC",
        "Trade or Economic Sanctions Endorsement",
        "Virus or Bacteria Exclusion - CGL",
        "Virus or Bacteria Exclusion - CPL",
        "Virus or Bacteria Exclusion - PL",
        #"Exclusion - Violation of Statutes that Govern E-Mails, Fax, Phone Calls",
        "Exclusion - Engineers, Architects or Surveyors",
        "Claims Notice Document",
        "Service of Suit",
        "Common Policy Conditions Endorsement",
        "Nuclear Energy Liability Exclusion",
        "Mold and Mildew Exclusion",
        "Minimum Premium Endorsement",
        "Employment Discrimination & Employment-Related Practices Exclusion",
        "Claims Notice Document",
        "Service of Suit",
        "PFAS Exclusion Endorsement"
    ]
}

ECC_EN = {
    'amountEndorsements': '342',
    'list': [
        "Common Policy Conditions",
        "Nuclear Energy Liability Exclusion",
        "Deductible Liability Insurance Endorsement",
        "Minimum Earned Premium Endorsement",
        "Automatic Additional Insured Owners Lessees or Contractors",
        "Automatic Waiver of Subrogation",
        "Transportation at Jobsite Endorsement",
        "Exclusion - Engineers Architects or Surveyors",
        "Exclusion - Access or Disclosure of Data",
        "OFAC",
        "Trade or Economic Sanctions Endorsement",
        "Extended Reporting Period Endorsement",
        "Specified Professional Services Endorsement",
        "Virus or Bacteria Exclusion - CGL",
        "Virus or Bacteria Exclusion - CPL",
        "Virus or Bacteria Exclusion - PL",
        "Exclusion - Violation of Statutes that Govern E-Mails, Fax, Phone Calls",
        "Claims Notice Document",
        "Service of Suit",
        "Exclusion - Designated Operations (Wrap-up)",
        "Temporary Workers",
        "New York Action Over Exclusion Endorsement",
        "Injury to Temporary Volunteer or Casual Worker Exclusion",
        "Paint Overspray Exclusion",
        "Designated Project Limitation Endorsement",
        "Terrorism Coverage Added Endorsement",
        "Maryland State Surplus Lines Notice Attachment",
        "Knowledge of Occurrence",
        "Designated Professional Services Exclusion",
        "Designated Premises Pollution Endorsement",
        "Designated Premises Exclusion",
        "Designated Operations Exclusion",
        "Designated Locations - General Aggregate",
        "Designated Covered Operations",
        "Designated Construction Proj Gen Aggregate Limit",
        "Deleting Named Insured Endorsement",
        "Dedicated Aggregate for a Designated Project",
        "Dedicated Aggregate - Per Project",
        "Cyber Liability Endorsement",
        "Natural Resource Damage Endorsement",
        "Responsible Insured Definition Amendment Endorsement",
        "Coverage for Injury to Co-Employees or Volunteer Workers",
        "Additional Insured PNC and Notice of Cancellation Endorsement",
        "Contractual Liability - Railroads",
        "Contingent Transportation Pollution Liability Coverage",
        "Workers Compensation/Employers Liability Limitation Endorsement",
        "Completed Operations Coverage Extension",
        "Governmental Immunity - Port Authority of NY & NJ",
        "Amendment of Insurance Agreement - Known Injury or Damage",
        "Cancellation Endorsement",
        "Additional Insured - Mortgagee Assignee or Receiver",
        "Care Custody Control Amendment",
        "Coverage For Entities with Leased Workers",
        "Boats Endorsement",
        "Primary and Noncontributory- Other Insurance Conditions",
        "Blanket Waiver of Transfer of Right of Recovery Against Others to Us",
        "Automatic Primary and Non-Contributory Endorsement",
        "Blanket Non-Owned Disposal Site Endorsement",
        "Blanket Addtl Insd-Owners Lessees or Contractors Completed Ops",
        "Blanket Addtl Insd State Political Subdivision",
        "Blanket Addtl Insd Owners Lessees or Contractors Completed Operations",
        "Blanket Additional Insured Owners Lessees or Contractors - Completed Operations",
        "Blanket Additional Insured - Owners Lessees or Contractors",
        "Bailees Coverage Form",
        "Spill Center Notice",
        "Additional Insured - Managers or Lessors of Premises",
        "Additional Insured - Lessor of Leased Equipment",
        "Additional Insured - Engineers Architects or Surveyors Endorsement",
        "Additional Insured - Designated Person or Organization",
        "Additional Insured - Grantor of Licenses",
        "Additional Insured - Grantor of Franchise",
        "Additional Insured - Co-Owner of Premises",
        "Additional Insured - Controlling Interest",
        "Added Named Insured Endorsement",
        "Added Coverage Part - E&O",
        "Added Coverage Part - CPL",
        "Added Coverage Part - CGL",
        "30 Day NOC Endorsement - No Endeavor to wording",
        "Exclusion - Saline Substances Contamination",
        "Exclusion - Failure to Supply",
        "Exclusion - Underground Resources and Equipment",
        "Additional Insured Endorsement - CPL",
        "Misdelivery of Liquid Products Coverage",
        "Additional Insured Blanket - CPL",
        "Exclusion - Contractors - Professional Liability",
        "Additional Insured - Vendors",
        "Additional Insured - State or Political Subdivisions",
        "Additional Insured - Owners or Other Interests From Whom Land Leased",
        "Additional Insured - Owners Lessees or Contractors - Completed Op's",
        "Worldwide Coverage with Specified Exceptions",
        "Waiver of Transfer of Right of Recovery Against Others to Us",
        "Additional Insured - Owners Lessees Form A",
        "Waiver of Subrogation Individual",
        "Waiver of Subrogation - E&O",
        "Waiver of Governmental Immunity",
        "Waiver of Deductible Endorsement",
        "Mold and Mildew Exclusion",
        "Virginia Financial Resp Biosolids",
        "TRIA Reinstatement Endorsement",
        "Transportation Pollution Liability Endorsement",
        "Compensation Collection Exclusion Endorsement",
        "Exclusion of Related Claims Endorsement",
        "Exclusion - Testing or Consulting Errors & Omissions",
        "Exclusion - Construction Mgmt Erors & Omissions",
        "Pyramiding of Limits Endorsement",
        "Previously Reported Claims Endorsement",
        "Technology Based Services Coverage Endorsement",
        "Supplemental Extended Reporting Period",
        "Subsidence Exclusion",
        "Sub Contractor as Insured",
        "Amendment of Address Endorsement",
        "Amendment of Policy Term Endorsement",
        "Amendment of Named Insured Endr",
        "Amendment of Limits Endorsement Project-Specific",
        "Amendment of Limits Endorsement Blanket",
        "Amendment of Coverage Territory - Worldwide Coverage Endorsement",
        "Amendment of Cancellation Notice Endorsement",
        "Sample Disposal Liability Endorsement",
        "Reporting Period Endorsement",
        "Reinstatement Endorsement",
        "Punitive or Exemplary Damages Amendment",
        "Professional Liability Claims Expense Limit",
        "Products (Pollution) Liability Coverage Endorsement",
        "Amendment of Occurrence Definition",
        "Primary and Non-Contributory Endorsement (project specific)",
        "Pesticide or Herbicide Applicators Coverage",
        "Notification of Cancellation to Certificate Holders",
        "Non-Owned Watercraft Endorsement",
        "Non-Owned Disposal Site Liability Endorsement",
        "Motor Vehicle Laws Endorsement",
        "General Amendatory Endt",
        "FLAT Cancellation Endorsement",
        "Fellow Employee Amendment Endorsement",
        "Extension of Coverage for Certain Specified Claims",
        "Extension of Coverage for Certain Occurrences",
        "Extended Policy Endorsement",
        "Exclusion of Services for a Related Person Firm or Organization",
        "Exclusion - XCU",
        "Exclusion - Projects by a Related Person Firm or Organization",
        "Extended Reporting Endorsement",
        "Mold Sublimit Endorsement",
        "Mold Deductible Endorsement",
        "Medical Monitoring Costs Endorsement",
        "Vacant Land/Rental Property Exclusion",
        "Exclusion - Data Processing Equipment Data Media or Computer Programs",
        "Material Change Endorsement - 60 Day",
        "Material Change Endorsement",
        "LSRP Professional Liability Endorsement",
        "Limited Contractual Liability Coverage",
        "In REM Coverage Endorsement",
        "Hired and Non-Owned Auto Liability Coverage",
        "Hired and Non-Owned Auto Liability $1M",
        "Hired and Non Owned Auto - 1mil/1mil limit",
        "Gulf of Mexico Endorsement",
        "Governmental Entity Endorsement",
        "Extended Reporting Period Endorsement",
        "Exclusion - Designated Products",
        "Exclusion - Designated Op's",
        "Employers Liability (Stop Gap) 1/1 limit",
        "Employee Benefit Liability - 1mil/1mil limit",
        "Electronic Data Liability Endorsement",
        "Low-Level Radioactive Waste Amendment",
        "ECC Terrorism Cancellation Endorsement",
        "Additional Insured-State or Governmental Agency or Subdivision",
        "Additional Insured Owners Lessees Automatic Status Endorsement",
        "Additional Insured-Manager of Lessors of Premises",
        "Exclusion - Fire Damage Legal Liability",
        "Employment Related Practices Exclusion",
        "Total Pollution Exclusion",
        "Additional Insured Individual",
        "Additional Insured- Engineers Architects or Surveyors",
        "Inspection Appraisal and Survey Companies",
        "Earlier Notice of Cancellation (60 days)",
        "Primary Insurance Endorsement",
        "Broad Form Named Insured",
        "Increased Limits Separate Retroactive Date",
        "Material Change Endorsement",
        "Designated Operations Covered By A Consolidated Insurance Program",
        "Hired and Non-Owned Auto - 2M Limit",
        "Premium Audit Endorsement",
        "Communicable Disease Exclusion",
        "Exclusion - Coverage C - Medical Payments",
        "Retroactive Dates for Scheduled Locations",
        "Exclusion - Communicable Disease with Mold exception",
        "Service of Suit",
        "Claims Notice Document",
        "PFAS Exclusion Endorsement"
    ]
}



# NY = {'amountEndorsements': '55',
#               'list': ['List','variable']}
# LA = {'amountEndorsements': '10',
#               'list': ['List','variable']}
# SF = {'amountEndorsements': '45',
#               'list': ['List','variable']}

def get_variables(env):
    if env == 'ECC_EN':
        return ECC_EN        
    elif env == 'ECC_VA':
        return ECC_VA
    else:
        # default variables
        return ECC_EN